### ISSUE TITLE
weights per data point in the nd grid case?

### ISSUE THREAD

**Issue by vincentschut** [espdev/csaps#24]
Hi, I'm using your package to fit a smoothing sline through gridded (2D) data points, but I'd like to assign an individual weight to each datapoint. However, I only seem to be able to assign weights to dimensions. When I pass a numpy array the size of ydata, I get an error: TypeError: 'weights' must be a sequence of the vectors.

Is there any possibility or workaroung to use the nd case while still using an individual weight per data point?

**Comment by espdev** [comment]
Hi Vincent,

Unfortunately, this is not possible in the used algorithm. In gridded data case firstly we perform computing univariate splines for all data vectors for the dimension at the time with the same weights vector. Secondary, we perform tensor product of univariate spline coefficients for all vectors for every dimension (compute coordinatewise spline). Therefore, we can set weights only for every dimension, but not for every data point.

https://github.com/espdev/csaps/blob/0b4eacccfdc11c54fc2348d6b2275547eb80bbc1/csaps/_sspndg.py#L220-L248

You can try to use [scipy.interpolate.SmoothBivariateSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.SmoothBivariateSpline.html#scipy.interpolate.SmoothBivariateSpline) instead of csaps for your 2D data case. This class allows you to set weights for every data point.

**Comment by vincentschut** [comment]
Clear, thanks for the explanation. I used csaps because I liked the implementation of the smoothing better than that from scipy (iirc it removes knots until the smoothing criterion is met). Will do some comparison though, thanks for the suggestion.

**Comment by nsn88** [comment]
**+1 for individual weights.**

My data is very noisy at some regions and this is affecting the final result. Guess I'll have to deal with scipy.interpolate.SmoothBivariateSpline.

**Comment by espdev** [comment]
@nsn88 also you can consider another smoothing methods instead of smoothing splines. For example, weighted local regression (see Matlab [lowess](https://www.mathworks.com/help/curvefit/lowess-smoothing.html) implementation for example), or Savitzky–Golay 2D filter (see my Python [sgolay2](https://github.com/espdev/sgolay2) implementation for example).
